### ISSUE TITLE
Maping a scalar to float results in 'AnyCodable does not conform to Decoder'

### ISSUE THREAD

**Issue by BerkeleyTrue** [maticzav/swift-graphql#111]
**Describe the bug**

I have a scalar mapping to Float for my generated code targeting BrainTrees api.

This doesn't seem to effect Int

The generated code results in
![image](https://user-images.githubusercontent.com/6775919/211239236-2b426757-ba14-4bf9-80d8-79d3684516d2.png)

The Int version for example
![image](https://user-images.githubusercontent.com/6775919/211239532-51f7455e-0008-40d4-9b0a-2676885e9027.png)

**To Reproduce**

Create a graphql scalar of Amount, then map Scalar to Float in config. Then generate api using CLI

**Expected behavior**

Generated code compiles without error

**Screenshots**

- Device: Macbook Pro 2015
- OS: MacOS 12.6.2 (21G320)
- Version 4.0.2
**Additional context**

XCode Version 14.2 (14C18)

**Comment by nordfogel** [comment]
We are facing a similar issue with Double decoding which is located in the frameworks `SwiftGraphQL/Document/Scalar.swift`

```
extension Double: GraphQLScalar {
		public init(fixedFrom codable: AnyCodable) throws {
				switch(codable.value) {
				case let value as Float:
					self = Double(value)
				case let value as Double:
					self = value
				default:
					let err = ScalarDecodingError.unexpectedScalarType(
							expected: "Double",
							received: codable.value
					)
					throw err
			}
	}
		
	public static let mockValue = 3.14
}
```

The GraphQL Schema states that the respective value for a certain property is supposed to be a `Double` however a simple single digit number is not interpreted as Double nor float within the upper decoding function. 

> fields
> min: Float!
> minimum value in the range

```
"values": {
   "min": 1
}
```

Instead, it is interpreted as an Integer, so we would like to propose the following change:

```
extension Double: GraphQLScalar {
		public init(fixedFrom codable: AnyCodable) throws {
				switch(codable.value) {
				case let value as Int:
					self = Double(value)
				case let value as Float:
					self = Double(value)
				case let value as Double:
					self = value
				default:
					let err = ScalarDecodingError.unexpectedScalarType(
							expected: "Double",
							received: codable.value
					)
					throw err
			}
	}
		
	public static let mockValue = 3.14
}
```

**Comment by BerkeleyTrue** [comment]
@rijo-42square I just would just go in and manually change the compiled code.

**Comment by maticzav** [comment]
@BerkeleyTrue SwiftGraphQL by default maps all `Float` GraphQL types to `Double` values in Swift. If you check the [spec](http://spec.graphql.org/October2021/#sec-Float), `Floats` represent a "signed double-precision finite values as specified by [IEEE 754](https://en.wikipedia.org/wiki/IEEE_floating_point)" Swift `Float`, on the other hand, represents "A single-precision, floating-point value type" ([source](https://developer.apple.com/documentation/swift/float)).

As a consequence, I decided to go with the [`Float` → `Double`](https://github.com/maticzav/swift-graphql/blob/3e26d207d410c1ec7e5f93ddab82361018e24c27/Sources/SwiftGraphQLCodegen/Generator/Scalar.swift#L38) mapping.

If I understand you correctly, you manually changed the mapping to map `Float` values to `Floats`. In that case, I suggest you check the [Custom Scalars](https://www.swift-graphql.com/docs/advanced/scalars) guide since SwiftGraphQL by default doesn't implement protocol conformance for `Floats`. You can see it [here](https://github.com/maticzav/swift-graphql/blob/3e26d207d410c1ec7e5f93ddab82361018e24c27/Sources/SwiftGraphQL/Document/Scalar.swift).

> On the side, I see in the other comment that you manually changed the code. Would you mind sharing what changes helped you get your code working? Do I understand your problem right?

---

@nordfogel if I understand you correctly, your issue is related to runtime error while the original post was about the type conformance. I'll defer the conversation to #120.
