### ISSUE TITLE
Alias issue

### ISSUE THREAD

**Issue by yonaskolb** [maticzav/swift-graphql#152]
Hi, I've got a question about aliases. Our server is having issues for some reason with the automatically hashed aliases on edge selections. Other aliases seem fine.

This is a snippet of the request body. Green works, red doesn't:
```diff
- "query": "query {\n  postsquery__19mo3grcmntt4: posts {\n    __typename\n    edgespostConnection__5zdq2eh8km7i: edges {...
+ "query": "query {\n  postsquery__19mo3grcmntt4: posts {\n    __typename\n    edges {...
+ "query": "query {\n  postsquery__19mo3grcmntt4: posts {\n    __typename\n    edges: edges {...
```
The red aliases case returns an empty array for the edges
```json
{
  "data": {
    "postsquery__19mo3grcmntt4": {
      "__typename": "PostConnection",
      "edgespostConnection__5zdq2eh8km7i": []
    }
  }
}
```

I'm aware this should be working on our end, and it must be an issue with our server implementation. Supposedly we're using https://gqlgen.com server side, but the team has yet to work out what the issue is. 

As a route to resolve this I tested disabling the hashed aliases in a fork by just returning the original name in `GraphQLField`, and everything seems to be working fine. 

```diff
public var alias: String? {
    switch self {
    case let .leaf(name, parent, arguments),
        let .composite(name, parent, _, arguments, _):
+        // using aliases that are different from the actual name breaks edges in our graph, disabling for now
+        return name
-        return "\(name.camelCase)\(parent.camelCase)_\(arguments.hash)"
    case .fragment:
        return nil
    }
}
```

My question is what issues will this cause if any? I assume the aliases are used for some kind of disambiguation. In what scenario would this cause problems?

**Comment by maticzav** [comment]
You are right, I added aliases as a way to deterministically disambiguate between different calls to the same field. GraphQLSpec doesn't restrict that and there's no other "easy" way of doing the disambiguation when you try to conceal GraphQL entirely.

Having used `elm-graphql` as inspiration, it seemed like a natural thing to do since it helps us cover more cases. Thinking about it now, it might be better to allow it as a flag (e.g. using the hashed variation by default but letting the devs opt-out).

The only real hiccup is that you MUST NOT call the same field twice in a single part of the query (which is obviously a super edge case for most developers).

---

Did you need to change anything else? It night make sense to extend the client and the builder.

**Comment by yonaskolb** [comment]
That makes sense. I can't imagine us querying the same field twice though. Would would be the use case of that? And if the hashing wasn't there wouldn't it just merge the duplicate calls?

I didn't need to change anything else to get it working, though I guess ideally it wouldn't even write the alias (which is now the same duplicate name) into the query, but that seemingly required a whole bunch of other code changes.
```diff
- field: field {...} // my fix
+ field {...} // ideal
```

**Comment by yonaskolb** [comment]
As another note, these hashed aliases would probably make http caching more difficult, especially as the Swift hashing used is non deterministic

**Comment by maticzav** [comment]
@yonaskolb do you know of any good alternative that we could use to deterministically hash fields? Preferably something in the standard library or something with low overhead?

**Comment by yonaskolb** [comment]
Perhaps a counter by field that increments on duplicate field access? And for the 0 case it wouldn't even use an alias? That would seem to solve both issues, but I don't know the intricacies of the system well enough to know if that would work. I also don't quite understand the need to create seperate aliases for multiple accesses so my picture of the situation is probably off.

**Comment by tuxi7x** [comment]
> Thinking about it now, it might be better to allow it as a flag (e.g. using the hashed variation by default but letting the devs opt-out).

I would also say that it would be great if the API users could decide whether they would like to use aliases or not, for multiple reasons:

- Caching, as said earlier
- Mocking - when working with mocked JSON responses, it is nearly impossible to decode the response with aliases right now
- Testing - Writing unit tests for queries (and decoding) is also really hard with aliases

> The only real hiccup is that you MUST NOT call the same field twice in a single part of the query (which is obviously a **super edge case** for most developers).

I agree that because of this reason it is not a bad idea to allow aliases to be turned off.

**Comment by shaps80** [comment]
@tuxi7x Great points! I personally also agree it would be better if the developer could determine the usage of aliases as well as what the generated query will eventually 'look' like. I'm exploring some new ideas for v6 that are aimed at improving the developer experience. I'll start a Discussion shortly and tag you all there next week, I think that's a better place for these discussions 👍

Thank you also @yonaskolb for raising this 👍

**Comment by yonaskolb** [comment]
This was closed as completed. Any updates on this one?
