### ISSUE TITLE
There are no changes listed for releases since 5.0.9

### ISSUE THREAD

**Issue by pokryfka** [maticzav/swift-graphql#177]
There are no changes listed for [5.0.9](https://github.com/maticzav/swift-graphql/releases/tag/5.0.9) and [5.0.10](https://github.com/maticzav/swift-graphql/releases/tag/5.0.10)

_Originally posted by @pokryfka in https://github.com/maticzav/swift-graphql/discussions/170#discussioncomment-7334882_

**Comment by shaps80** [comment]
Fixed

**Comment by pokryfka** [comment]
@shaps80  This is more generic issue. I think its critical to know what changed in new releases.

The project used to have decent releases notes with references to PRs, example https://github.com/maticzav/swift-graphql/releases?page=2 

Some of the nicest release notes are made by Apple's swift-server team:
- https://github.com/apple/swift-nio/releases
- https://github.com/swift-server/async-http-client/releases

**Comment by shaps80** [comment]
I understand, in practice I've found them less valuable across smaller scale libraries since developers don't tend to read them unless they have an issue lol.

That being said, I'm not suggesting we stop including them, AFAICT they're somewhat automated but for some reason the commits were not included automatically when I made that release I guess.

Regardless, I saw your issue, updates the release notes and close this issue.

We have something implemented already, so I don't know why you're pushing this issue atm sorry?
