### ISSUE TITLE
Generic parameter 'T'/'TypeLock' could not be inferred

### ISSUE THREAD

**Issue by atomkirk** [maticzav/swift-graphql#192]
**Describe the bug**
I've tried to copy your "feeds" example into my project as closely and as simply as possible, but I'm getting this error and can't figure out why 
<img width="1643" alt="CleanShot 2024-01-05 at 09 46 48@2x" src="https://github.com/maticzav/swift-graphql/assets/2091439/36269629-19e1-4122-9650-994b7b7d2941">

**To Reproduce**
Create a new project with all the latest xcode & ios versions, latest swift-graphql version, etc and try and build a simple query builder following the examples in the doc and repo

**Expected behavior**
no error

**Desktop (please complete the following information):**

- OS: macOS
- Version 13.6.3

**Xcode**
Version: 15.1 (15C65)

**Comment by atomkirk** [comment]
hmm, when I clone the repo I can build the tsn example… so it must be a problem in my code

**Comment by atomkirk** [comment]
hmm, I'm wonder if its having a problem with the schema [absinthe](https://absinthe-graphql.org/) is generating

**Comment by atomkirk** [comment]
[API.swift.zip](https://github.com/maticzav/swift-graphql/files/13844979/API.swift.zip)

do you see anything wrong with what was generated here?

**Comment by atomkirk** [comment]
sorry, my query was wrong.I've updated to this and getting same error:

```swift
    static var upcoming = Selection.Query<[Meeting]> {
        try $0.meetings(filters: ~nil, selection: Meeting.selection.list)
    }
```

**Comment by atomkirk** [comment]
yeah, its a problem with my generated API.swift file. I replaced my API.swift file with the one from thesocialnetwork, changed Meeting to Message, and the project compiles just fine

**Comment by atomkirk** [comment]
ok figured it out. had to do this:
```
    static var upcoming = Selection.RootQueryType<[Meeting]> {
        try $0.meetings(filters: ~nil, selection: Meeting.selection.list)
    }
```

Thats pretty confusing

**Comment by shaps80** [comment]
@atomkirk looks like you solved it before I could get back to this haha. Glad to hear it.

I agree with the confusion though. There are some details that are out-of-date in that project I think, but also it's not the most intuitive API for that since the learning curve is a little steep.

Good news is? I'm working on this, on a v6 that is a huge departure from the current approach but removes this confusion considerably.

Keep an eye on the Roadmap ticket or Discussions if you're keen to stay up-to-date.

Appreciate your support and thanks for reaching out, glad you managed to sort it yourself 👍

**Comment by atomkirk** [comment]
Thanks for your response!
