### ISSUE TITLE
Allow generation of schema from JSON file

### ISSUE THREAD

**Issue by AlexGustafsson** [maticzav/swift-graphql#48]
**Is your feature request related to a problem? Please describe.**
The current generation tool relies on executing a query on the target API endpoint. This may cause authentication issues, rate limiting etc.

**Describe the solution you'd like**
I'd like to be able to generate a tool based on provided JSON data, such as GitHub's official GraphQL API schema: https://github.com/octokit/graphql-schema/blob/master/schema.json.

**Describe alternatives you've considered**
Switching library, using other tool for generating the code, host the schema to use existing functionality requiring the endpoint to be active.

**Additional context**
-

**Comment by maticzav** [comment]
Hey! 👋 

Could you explain why authentication is an issue? I understand that this feature would be great, but at the same time, I don't see how it is blocking anyone. We support authentication and rate-limiting shouldn't be an issue. Maybe I am missing something ...

**Comment by simpers** [comment]
I'll agree with @AlexGustafsson that this feature would be good to have.

We generate our schema from the server-side as a JSON file that can then be used by the client(s) instead of forcing us to temporarily host the dev server (for example) for the tool to fetch it and then shut it down. Some might not even be able to run the dev server, actually. So this is my main reason. Less friction in the team.

**Comment by maticzav** [comment]
The new version of SwiftGraphQL now supports loading schema from the JSON introspection file.
