### ISSUE TITLE
Add a way to access response headers

### ISSUE THREAD

**Issue by ceopaludetto** [maticzav/swift-graphql#57]
**Is your feature request related to a problem? Please describe.**
I want to access response headers because I need to save authorization tokens from server

**Describe the solution you'd like**
Would be nice if `completionHandler` of send function return the `HTTPURLResponse` which exposes the property `allHeaderFields`

**Describe alternatives you've considered**
I've wrote a custom `URLProtocol` to intercept the request and the response with custom logic to add my tokens on keychain

**Comment by maticzav** [comment]
👋 

The new version let's you take complete control over how you send and receive your request. Instead of hiding the networking part, the library's core (the whole library in the previous version) only handles selection and decoding. You can find the methods that (I think) you are looking for in https://github.com/maticzav/swift-graphql/blob/main/Sources/SwiftGraphQL/HTTP.swift.

Feel free to reopen this issue or add comments if you need more help 🙂
