### ISSUE TITLE
How do I display GraphQLError message?

### ISSUE THREAD

**Issue by Matthewspear** [maticzav/swift-graphql#77]
**Describe the bug**
My GraphQL server has a case that returns an error, and in the app this is received as a GraphQLError I want to display the error message accompanying it.

Trying to access the message on GraphQLError just says:
`'message' is inaccessible due to 'internal' protection level`

Pointing to Result.swift, line 49

**Expected behaviour**
I would expect message to be accessible or printable either as public or via localisedDescription similar to system behaviour of Error, NSError types.

---

I don't quite understand but what is the use of `message` if only internal?

Let me know if I am missing something or there is a better approach.

Also happy to make a pull request making it public / helper function for accessing errors!

**Comment by maticzav** [comment]
Hi @Matthewspear 👋 ,

Thank you for opening this issue! I think this should no longer be a problem in the new version. Let me know if the new version solves your problems and feel free to reopen the issue otherwise. 🙂

**Comment by big-javascript-fan** [comment]
@maticzav 
I also have same issue, on the backend, it is throwing ConflictException from Nest.js server with some messages.
I need to catch that error message on error object, but I still can't get because on receiveCompletion, what I got is just ObjectDecodingError. On which block, can I get the GraphQLError or CombinedError type?
Can you please provide me some sample code to check with?
